const pizzas = [
    // PIZZA CATEGORY - Premium Pizzas
    {
      id: 1,
      image: "../../public/pizza-1.jpg",
      title: "Pepperoni Supreme",
      rating: 4.8,
      price: 450,
      category: "pizza",
      subcategory: "premium",
      detail: "Our signature Pepperoni Supreme features hand-tossed dough, San Marzano tomato sauce, premium mozzarella, and authentic Italian pepperoni.",
      ingredients: ["Hand-tossed dough", "San Marzano tomatoes", "Premium mozzarella", "Italian pepperoni"],
      prepTime: "15-20 minutes",
      spiceLevel: "Medium",
      calories: 320,
      popular: true,
      new: false
    },
    {
      id: 2,
      image: "../../public/pizza-2.jpg",
      title: "Margherita Classica",
      rating: 4.9,
      price: 380,
      category: "pizza",
      subcategory: "classic",
      detail: "The timeless Margherita celebrates simplicity with fresh San Marzano tomatoes, buffalo mozzarella, and fresh basil.",
      ingredients: ["San Marzano tomatoes", "Buffalo mozzarella", "Fresh basil", "Extra virgin olive oil"],
      prepTime: "12-15 minutes",
      spiceLevel: "Mild",
      calories: 280,
      popular: true,
      new: false
    },
    {
      id: 3,
      image: "../../public/pizza-3.jpg",
      title: "Garden Fresh Veggie",
      rating: 4.6,
      price: 420,
      category: "pizza",
      subcategory: "vegetarian",
      detail: "Loaded with farm-fresh vegetables including roasted bell peppers, mushrooms, red onions, black olives, and spinach.",
      ingredients: ["Bell peppers", "Mushrooms", "Red onions", "Black olives", "Cherry tomatoes", "Spinach"],
      prepTime: "18-22 minutes",
      spiceLevel: "Mild",
      calories: 250,
      popular: false,
      new: true
    },
    {
      id: 4,
      image: "../../public/pizza-4.jpg",
      title: "Tropical Hawaiian",
      rating: 4.3,
      price: 460,
      category: "pizza",
      subcategory: "specialty",
      detail: "A perfect balance of sweet and savory with premium ham, fresh pineapple chunks, and mozzarella cheese.",
      ingredients: ["Premium ham", "Fresh pineapple", "Mozzarella cheese", "Hawaiian sauce"],
      prepTime: "16-20 minutes",
      spiceLevel: "Mild",
      calories: 340,
      popular: false,
      new: false
    },
    {
      id: 5,
      image: "../../public/pizza-5.jpg",
      title: "Meat Lovers Feast",
      rating: 4.7,
      price: 520,
      category: "pizza",
      subcategory: "premium",
      detail: "A carnivore's dream featuring pepperoni, Italian sausage, smoked bacon, ham, and ground beef.",
      ingredients: ["Pepperoni", "Italian sausage", "Smoked bacon", "Premium ham", "Ground beef"],
      prepTime: "20-25 minutes",
      spiceLevel: "Medium",
      calories: 480,
      popular: true,
      new: false
    },
    {
      id: 6,
      image: "../../public/pizza-6.jpg",
      title: "BBQ Chicken Deluxe",
      rating: 4.5,
      price: 480,
      category: "pizza",
      subcategory: "specialty",
      detail: "Grilled chicken breast marinated in our house BBQ sauce, topped with red onions and cilantro.",
      ingredients: ["BBQ chicken", "Red onions", "Cilantro", "Mozzarella", "Cheddar"],
      prepTime: "18-22 minutes",
      spiceLevel: "Medium",
      calories: 380,
      popular: false,
      new: true
    },
    {
      id: 7,
      image: "../../public/pizza-7.jpg",
      title: "Creamy Alfredo Supreme",
      rating: 4.4,
      price: 440,
      category: "pizza",
      subcategory: "specialty",
      detail: "Rich and creamy Alfredo sauce made with real butter, heavy cream, and aged parmesan.",
      ingredients: ["Alfredo sauce", "Grilled chicken", "Sautéed mushrooms", "Fresh spinach"],
      prepTime: "16-20 minutes",
      spiceLevel: "Mild",
      calories: 420,
      popular: false,
      new: false
    },
    {
      id: 8,
      image: "../../public/pizza-8.jpg",
      title: "Ultimate Supreme",
      rating: 4.8,
      price: 550,
      category: "pizza",
      subcategory: "premium",
      detail: "Our most loaded pizza featuring pepperoni, sausage, bell peppers, onions, mushrooms, and black olives.",
      ingredients: ["Pepperoni", "Sausage", "Bell peppers", "Onions", "Mushrooms", "Black olives"],
      prepTime: "20-25 minutes",
      spiceLevel: "Medium-Hot",
      calories: 450,
      popular: true,
      new: false
    },
    {
      id: 9,
      image: "../../public/pizza1.jpeg",
      title: "Buffalo Chicken Pizza",
      rating: 4.4,
      price: 410,
      category: "pizza",
      subcategory: "specialty",
      detail: "Spicy and tangy pizza topped with shredded buffalo chicken and melted mozzarella.",
      ingredients: ["Buffalo chicken", "Mozzarella", "Ranch dressing", "Celery"],
      prepTime: "16-20 minutes",
      spiceLevel: "Hot",
      calories: 360,
      popular: false,
      new: true
    },
    {
      id: 10,
      image: "../../public/pizza2.jpeg",
      title: "Four Cheese Delight",
      rating: 4.6,
      price: 425,
      category: "pizza",
      subcategory: "vegetarian",
      detail: "A blend of mozzarella, cheddar, parmesan, and gorgonzola cheeses creating a rich flavor profile.",
      ingredients: ["Mozzarella", "Cheddar", "Parmesan", "Gorgonzola"],
      prepTime: "14-18 minutes",
      spiceLevel: "Mild",
      calories: 380,
      popular: false,
      new: false
    },

    // BURGER CATEGORY - Gourmet Burgers
    {
      id: 11,
      image: "../../public/burger-1.jpg",
      title: "Classic Beef Deluxe",
      rating: 4.6,
      price: 320,
      category: "burger",
      subcategory: "beef",
      detail: "Premium Angus beef patty grilled to perfection, topped with aged cheddar and crispy bacon.",
      ingredients: ["Angus beef patty", "Aged cheddar", "Crispy bacon", "Lettuce", "Tomato"],
      prepTime: "12-15 minutes",
      spiceLevel: "Mild",
      calories: 680,
      popular: true,
      new: false
    },
    {
      id: 12,
      image: "../../public/burger-2.jpg",
      title: "Chicken Deluxe Supreme",
      rating: 4.5,
      price: 360,
      category: "burger",
      subcategory: "chicken",
      detail: "Crispy chicken breast marinated in buttermilk, topped with Swiss cheese and avocado.",
      ingredients: ["Crispy chicken breast", "Swiss cheese", "Avocado", "Chipotle mayo"],
      prepTime: "15-18 minutes",
      spiceLevel: "Medium",
      calories: 720,
      popular: false,
      new: true
    },
    {
      id: 13,
      image: "../../public/burger-3.jpg",
      title: "Veggie Power Burger",
      rating: 4.4,
      price: 280,
      category: "burger",
      subcategory: "vegetarian",
      detail: "Plant-based patty made from black beans, quinoa, and vegetables.",
      ingredients: ["Plant-based patty", "Vegan cheese", "Avocado", "Sprouts"],
      prepTime: "10-12 minutes",
      spiceLevel: "Mild",
      calories: 520,
      popular: false,
      new: false
    },
    {
      id: 14,
      image: "../../public/burger-1.jpg",
      title: "BBQ Bacon Cheeseburger",
      rating: 4.7,
      price: 380,
      category: "burger",
      subcategory: "beef",
      detail: "Juicy beef patty with crispy bacon, melted cheddar, and BBQ sauce.",
      ingredients: ["Beef patty", "Crispy bacon", "Cheddar cheese", "BBQ sauce"],
      prepTime: "15-18 minutes",
      spiceLevel: "Medium",
      calories: 850,
      popular: true,
      new: false
    },

    // PASTA CATEGORY - Italian Classics
    {
      id: 15,
      image: "../../public/pasta-1.jpg",
      title: "Spaghetti Carbonara",
      rating: 4.8,
      price: 420,
      category: "pasta",
      subcategory: "classic",
      detail: "Authentic Roman pasta with eggs, pancetta, aged pecorino cheese, and black pepper.",
      ingredients: ["Fresh spaghetti", "Eggs", "Pancetta", "Pecorino cheese"],
      prepTime: "12-15 minutes",
      spiceLevel: "Mild",
      calories: 580,
      popular: true,
      new: false
    },
    {
      id: 16,
      image: "../../public/pasta-2.jpg",
      title: "Penne Arrabbiata",
      rating: 4.6,
      price: 380,
      category: "pasta",
      subcategory: "spicy",
      detail: "Spicy penne pasta with garlic, red chili peppers, and San Marzano tomatoes.",
      ingredients: ["Penne pasta", "Garlic", "Red chili peppers", "San Marzano tomatoes"],
      prepTime: "10-12 minutes",
      spiceLevel: "Hot",
      calories: 450,
      popular: false,
      new: true
    },
    {
      id: 17,
      image: "../../public/pasta-3.jpg",
      title: "Fettuccine Alfredo",
      rating: 4.7,
      price: 400,
      category: "pasta",
      subcategory: "creamy",
      detail: "Rich and creamy fettuccine with butter, heavy cream, and aged parmesan cheese.",
      ingredients: ["Fettuccine pasta", "Butter", "Heavy cream", "Aged parmesan"],
      prepTime: "12-15 minutes",
      spiceLevel: "Mild",
      calories: 650,
      popular: true,
      new: false
    },
    {
      id: 18,
      image: "../../public/pasta-1.jpg",
      title: "Seafood Linguine",
      rating: 4.9,
      price: 480,
      category: "pasta",
      subcategory: "seafood",
      detail: "Fresh linguine with mixed seafood including shrimp, mussels, and calamari.",
      ingredients: ["Linguine pasta", "Shrimp", "Mussels", "Calamari"],
      prepTime: "15-18 minutes",
      spiceLevel: "Mild",
      calories: 520,
      popular: false,
      new: true
    },

    // APPETIZERS CATEGORY - Starters & Sides
    {
      id: 19,
      image: "../../public/pizza-1.jpg",
      title: "Garlic Bread Supreme",
      rating: 4.5,
      price: 180,
      category: "appetizer",
      subcategory: "bread",
      detail: "Fresh Italian bread brushed with garlic butter, topped with mozzarella cheese.",
      ingredients: ["Italian bread", "Garlic butter", "Mozzarella", "Herbs"],
      prepTime: "8-10 minutes",
      spiceLevel: "Mild",
      calories: 320,
      popular: true,
      new: false
    },
    {
      id: 20,
      image: "../../public/burger-2.jpg",
      title: "Buffalo Wings",
      rating: 4.6,
      price: 320,
      category: "appetizer",
      subcategory: "wings",
      detail: "Crispy chicken wings tossed in our signature buffalo sauce.",
      ingredients: ["Chicken wings", "Buffalo sauce", "Celery sticks"],
      prepTime: "15-18 minutes",
      spiceLevel: "Hot",
      calories: 480,
      popular: true,
      new: false
    },
    {
      id: 21,
      image: "../../public/pasta-2.jpg",
      title: "Mozzarella Sticks",
      rating: 4.4,
      price: 250,
      category: "appetizer",
      subcategory: "cheese",
      detail: "Golden fried mozzarella sticks with crispy breadcrumb coating.",
      ingredients: ["Mozzarella cheese", "Breadcrumbs", "Marinara sauce"],
      prepTime: "6-8 minutes",
      spiceLevel: "Mild",
      calories: 380,
      popular: false,
      new: true
    },
    {
      id: 22,
      image: "../../public/drink-1.jpg",
      title: "Caesar Salad",
      rating: 4.3,
      price: 220,
      category: "appetizer",
      subcategory: "salad",
      detail: "Fresh romaine lettuce with house-made Caesar dressing and croutons.",
      ingredients: ["Romaine lettuce", "Caesar dressing", "Croutons", "Parmesan"],
      prepTime: "5-7 minutes",
      spiceLevel: "Mild",
      calories: 280,
      popular: false,
      new: false
    },

    // DESSERTS CATEGORY - Sweet Treats
    {
      id: 23,
      image: "../../public/drink-2.jpg",
      title: "Tiramisu",
      rating: 4.8,
      price: 180,
      category: "dessert",
      subcategory: "cake",
      detail: "Classic Italian dessert with layers of coffee-soaked ladyfingers and mascarpone cream.",
      ingredients: ["Ladyfingers", "Mascarpone cheese", "Coffee", "Cocoa powder"],
      prepTime: "5 minutes",
      spiceLevel: "Mild",
      calories: 420,
      popular: true,
      new: false
    },
    {
      id: 24,
      image: "../../public/drink-3.jpg",
      title: "Chocolate Lava Cake",
      rating: 4.9,
      price: 200,
      category: "dessert",
      subcategory: "cake",
      detail: "Warm chocolate cake with a molten chocolate center, served with vanilla ice cream.",
      ingredients: ["Dark chocolate", "Butter", "Eggs", "Vanilla ice cream"],
      prepTime: "8-10 minutes",
      spiceLevel: "Mild",
      calories: 580,
      popular: true,
      new: true
    },
    {
      id: 25,
      image: "../../public/drink-4.jpg",
      title: "Cannoli",
      rating: 4.7,
      price: 160,
      category: "dessert",
      subcategory: "pastry",
      detail: "Crispy pastry shells filled with sweet ricotta cheese and chocolate chips.",
      ingredients: ["Pastry shells", "Ricotta cheese", "Chocolate chips", "Powdered sugar"],
      prepTime: "3-5 minutes",
      spiceLevel: "Mild",
      calories: 320,
      popular: false,
      new: false
    },

    // DRINKS CATEGORY - Beverages
    {
      id: 26,
      image: "../../public/drink-1.jpg",
      title: "Fresh Orange Juice",
      rating: 4.8,
      price: 120,
      category: "drink",
      subcategory: "juice",
      detail: "Freshly squeezed orange juice from premium oranges, rich in vitamin C.",
      ingredients: ["Fresh oranges"],
      prepTime: "2-3 minutes",
      spiceLevel: "None",
      calories: 110,
      popular: true,
      new: false
    },
    {
      id: 27,
      image: "../../public/drink-2.jpg",
      title: "Tropical Mango Smoothie",
      rating: 4.6,
      price: 200,
      category: "drink",
      subcategory: "smoothie",
      detail: "Creamy mango smoothie blended with Greek yogurt, honey, and vanilla.",
      ingredients: ["Fresh mango", "Greek yogurt", "Honey", "Vanilla"],
      prepTime: "3-5 minutes",
      spiceLevel: "None",
      calories: 180,
      popular: false,
      new: true
    },
    {
      id: 28,
      image: "../../public/drink-3.jpg",
      title: "Strawberry Milkshake",
      rating: 4.5,
      price: 220,
      category: "drink",
      subcategory: "milkshake",
      detail: "Rich and creamy strawberry milkshake made with fresh strawberries.",
      ingredients: ["Fresh strawberries", "Vanilla ice cream", "Whole milk"],
      prepTime: "3-4 minutes",
      spiceLevel: "None",
      calories: 320,
      popular: true,
      new: false
    },
    {
      id: 29,
      image: "../../public/drink-4.jpg",
      title: "Iced Caramel Macchiato",
      rating: 4.7,
      price: 180,
      category: "drink",
      subcategory: "coffee",
      detail: "Premium espresso with steamed milk, vanilla syrup, and caramel drizzle.",
      ingredients: ["Espresso", "Steamed milk", "Vanilla syrup", "Caramel sauce"],
      prepTime: "4-5 minutes",
      spiceLevel: "None",
      calories: 150,
      popular: false,
      new: true
    },
    {
      id: 30,
      image: "../../public/drink-5.jpg",
      title: "Premium Green Tea",
      rating: 4.4,
      price: 100,
      category: "drink",
      subcategory: "tea",
      detail: "High-quality green tea leaves steeped to perfection, rich in antioxidants.",
      ingredients: ["Premium green tea leaves", "Hot water"],
      prepTime: "2-3 minutes",
      spiceLevel: "None",
      calories: 5,
      popular: false,
      new: false
    },
    {
      id: 31,
      image: "../../public/drink-7.jpg",
      title: "Sparkling Lemonade",
      rating: 4.3,
      price: 140,
      category: "drink",
      subcategory: "soda",
      detail: "Refreshing sparkling lemonade made with fresh lemon juice and sparkling water.",
      ingredients: ["Fresh lemon juice", "Sparkling water", "Natural sweetener"],
      prepTime: "2-3 minutes",
      spiceLevel: "None",
      calories: 80,
      popular: false,
      new: true
    },
    {
      id: 32,
      image: "../../public/drink-8.jpg",
      title: "Chocolate Milkshake",
      rating: 4.8,
      price: 240,
      category: "drink",
      subcategory: "milkshake",
      detail: "Rich and indulgent chocolate milkshake made with premium cocoa powder.",
      ingredients: ["Premium cocoa powder", "Chocolate ice cream", "Whole milk"],
      prepTime: "3-4 minutes",
      spiceLevel: "None",
      calories: 450,
      popular: true,
      new: false
    },

    // SALADS CATEGORY - Fresh & Healthy
    {
      id: 33,
      image: "../../public/pizza-3.jpg",
      title: "Mediterranean Quinoa Bowl",
      rating: 4.6,
      price: 280,
      category: "salad",
      subcategory: "grain",
      detail: "Nutritious quinoa bowl with cherry tomatoes, cucumber, olives, and feta cheese.",
      ingredients: ["Quinoa", "Cherry tomatoes", "Cucumber", "Olives", "Feta cheese"],
      prepTime: "8-10 minutes",
      spiceLevel: "Mild",
      calories: 380,
      popular: false,
      new: true
    },
    {
      id: 34,
      image: "../../public/pasta-1.jpg",
      title: "Caprese Salad",
      rating: 4.7,
      price: 240,
      category: "salad",
      subcategory: "fresh",
      detail: "Classic Italian salad with fresh mozzarella, ripe tomatoes, and fresh basil.",
      ingredients: ["Fresh mozzarella", "Ripe tomatoes", "Fresh basil", "Balsamic glaze"],
      prepTime: "5-7 minutes",
      spiceLevel: "Mild",
      calories: 220,
      popular: true,
      new: false
    }
    
];
export default pizzas;

export const pizzas1 = [
  {
    id: 1,
    image: "../../public/pizza1.jpeg",
    title: "Pepperoni Pizza",
    rating: 4.5,
    price: 399
  },
  {
    id: 2,
    image: "../../public/drink-7.jpg",
    title: "Lemon Soda Juice",
    rating: 4.8,
    price: 400
  },
  {
    id: 3,
    image: "../../public/burger-1.jpg",
    title: "Vegetarian Burger",
    rating: 5.2,
    price: 250
  },
  {
    id: 4,
    image: "../../public/pasta-1.jpg",
    title: "Pasta",
    rating: 3.8,
    price: 420
  },
];